oglasise2/oglasise/oglasi/urls.py
from django.urls import path
from . import views

app_name = 'oglasi_app'

urlpatterns = [
    path('', views.svi_oglasi, name='svi_oglasi'),
    path('kategorije/', views.kategorje, name='kategorije'),
    path('komentari/', views.komentari, name='komentari'),
    path('korisnici/', views.korisnici, name='korisnici'),
    path('oglas/<int:id>', views.oglas, name='oglas'),
    path('del_kategorija/<int:id>', views.del_kategorija, name='del_kategorija'),
    path('edit_kategorija/<int:id>', views.edit_kategorija, name='edit_kategorija'),
]

oglasise2/oglasise/oglasise/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('oglasi.urls')),
]

oglasise2/oglasise/oglasi/models.py
from django.db import models
from django.contrib.auth.models import User

class Kategorija (models.Model):
    datumDodavanja = models.DateTimeField(auto_now_add=True)
    datumIzmene = models.DateTimeField(auto_now=True)
    naziv = models.CharField(max_length=30)


class Oglas (models.Model):
    naslov = models.CharField(max_length=30)
    kategorija = models.ForeignKey(Kategorija, on_delete=models.CASCADE)
    opis = models.CharField(max_length=120)
    mesto = models.CharField(max_length=30)
    datumDodavanja = models.DateTimeField(auto_now_add=True)
    datumIzmene = models.DateTimeField(auto_now=True)
    korisnik = models.ForeignKey(User, on_delete=models.CASCADE)


class Komentar (models.Model):
    datumDodavanja = models.DateTimeField(auto_now_add=True)
    datumIzmene = models.DateTimeField(auto_now=True)
    ocena = models.IntegerField()
    tekst = models.CharField(max_length=100)
    korisnik = models.ForeignKey(User, on_delete=models.CASCADE)
    oglas = models.ForeignKey(Oglas, on_delete=models.CASCADE)

oglasise2/oglasise/oglasi/forms.py
from django.forms import ModelForm
from .models import Kategorija, Oglas, Komentar


class KategorijaForm(ModelForm):
    class Meta:
        model = Kategorija
        fields = ['naziv']


class OglasForm(ModelForm):
    class Meta:
        model = Oglas
        fields = ['naslov', 'opis', 'mesto']


class KomentarForm(ModelForm):
    class Meta:
        model = Komentar
        fields = ['ocena', 'tekst']

oglasise2/oglasise/oglasi/views.py
from django.shortcuts import render, get_object_or_404
from .models import Oglas, Kategorija, Komentar
from django.contrib.auth import get_user_model
from .forms import KategorijaForm


def svi_oglasi(req):
    oglasi = Oglas.objects.all()
    labels = []
    data = []

    for o in oglasi:
        if not o.mesto in labels:
            labels.append(o.mesto)

    for m in labels:
        i = 0
        for o in oglasi:
            if o.mesto == m:
                i += 1
        data.append(i)

    return render(req, 'svi_oglasi.html', {'oglasi': oglasi, 'labels': labels, 'data': data})


def kategorje(req):
    labels = []
    data = []

    kategorije = Kategorija.objects.all()
    oglasi = Oglas.objects.all()
    for k in kategorije:
        labels.append(k.naziv)
        i = 0
        for o in oglasi:
            if o.kategorija_id == k.id:
                i+=1
        data.append(i)

    if req.method == 'POST':
        forma = KategorijaForm(req.POST)

        if forma.is_valid():
            m = Kategorija(naziv=forma.cleaned_data['naziv'])
            m.save()
            return render(req, 's_add.html')
        else:
            return render(req, 'kategorije.html',{'labels': labels, 'data': data, 'kategorije': kategorije, 'form': forma})
    else:
        forma = KategorijaForm()
        return render(req, 'kategorije.html', {'labels': labels, 'data': data, 'kategorije': kategorije, 'form': forma})


def komentari(req):
    labels = []
    data = []
    kom = Komentar.objects.all()
    ogl = Oglas.objects.all()

    for o in ogl:
        labels.append(o.naslov)
        i = 0
        for k in kom:
            if k.oglas_id == o.id:
                i = i+1
        data.append(i)

    return render(req, 'komentari.html', {'labels': labels,'data': data,'komentari': kom})

def korisnici(req):
    labels = []
    data = []
    data2 = []
    User = get_user_model()
    users = User.objects.all()
    kom = Komentar.objects.all()
    ogl = Oglas.objects.all()

    for u in users:
        labels.append(u.username)
        i = 0
        oc = 0
        br = 0
        for o in ogl:
            if o.korisnik_id == u.id:
                i = i+1
                for k in kom:
                    if k.oglas_id == o.id:
                        br += 1
                        oc += k.ocena
        data.append(i)
        if not br == 0:
            data2.append(oc/br)

    return render(req, 'korisnici.html', {'labels': labels,'data': data,'korisnici': users, 'data2': data2})

def oglas(req, id):
    tmp = get_object_or_404(Oglas, id=id)
    txt = ("oglas id: " + str(tmp.id))
    kom = Komentar.objects.filter(oglas_id = id)
    brkom = 0
    zocena = 0
    labels = [1, 2, 3, 4, 5]
    data = []

    for k in kom:
        brkom += 1
        zocena += k.ocena
    pocena = 0
    if not brkom==0:
        pocena = zocena/brkom

    for le in labels:
        i = 0
        for k in kom:
            if k.ocena == le:
                i+=1
        data.append(i)

    return render(req, 'oglas.html', {'oglas': tmp, 'page_title': txt, 'pocena': pocena, 'komentari':kom, 'labels': labels,'data': data})


def del_kategorija(req, id):
    k = get_object_or_404(Kategorija, id=id)
    k.delete()
    return render(req, 's_delete.html', {})

def edit_kategorija(req, id):
    labels = []
    data = []

    kategorije = Kategorija.objects.all()
    oglasi = Oglas.objects.all()
    for k in kategorije:
        labels.append(k.naziv)
        i = 0
        for o in oglasi:
            if o.kategorija_id == k.id:
                i += 1
        data.append(i)

    if req.method == 'POST':
        forma = KategorijaForm(req.POST)

        if forma.is_valid():
            m = Kategorija.objects.get(id=id)
            m.naziv = forma.cleaned_data['naziv']
            m.save()
            return render(req, 's_edit.html')
        else:
            return render(req, 'kategorije.html',
                          {'labels': labels, 'data': data, 'kategorije': kategorije, 'form': forma, 'id': id})
    else:
        tmp = get_object_or_404(Kategorija, id=id)
        forma = KategorijaForm(instance=tmp)
        return render(req, 'kategorije.html',
                      {'labels': labels, 'data': data, 'kategorije': kategorije, 'form': forma, 'id': id})

oglasise2/oglasise/oglasi/templates/kategorije.html
{%  extends 'master.html' %}

{% block title %}
   Kategorije
{% endblock %}

{%  block content %}
    <h2>KATEGORIJE </h2>
    <br>

    <div>
        <h3>Raspodela oglasa po kategorijama:</h3>
        <canvas id="pie-chart"></canvas>
        <br>
        <h3>Sve kategorije:</h3>
        <table class="table">
          <thead style="background-color: #215987; color: #e5e1dc">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Naziv</th>
                <th scope="col">Akcije</th>
            </tr>
          </thead>
          <tbody>
            {% for k in kategorije %}
                <tr style="transform: rotate(0);">
                    <td>{{ k.id }}</td>
                    <td>{{ k.naziv }}</td>
                     <td>
                        <a  href="{% url 'oglasi_app:del_kategorija' k.id %}">
                            <span class="badge badge-danger">Delete</span>
                        </a>
                         <a  href="{% url 'oglasi_app:edit_kategorija' k.id%}">
                            <span class="badge btn-info">Edit</span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
    {% if form.naziv.value is None %}
    <form method="post"  action="{% url 'oglasi_app:kategorije' %}"   >
        {% csrf_token %}
        <h3>Dodaj kategoriju:</h3>
        <div class="container" style="text-align: center; width: 400px; margin-bottom: 20px" >
            <label>{{ form.naziv.label_tag }}</label>
            <input type="text" required class="form-control" id="{{ form.naziv.id_for_label }}" name="{{ form.naziv.name }}" >
            {% if form.naziv.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.naziv.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <input type="submit" class="btn btn-primary btn-lg" value="Dodaj" style=" width: 370px; margin-top: 20px"/>
        </div>
    </form>
    {% endif %}

    {% if form.naziv.value is not None %}
        <form method="post"  action="{% url 'oglasi_app:edit_kategorija' id %}"   >
        {% csrf_token %}
        <h3>Dodaj kategoriju:</h3>
        <div class="container" style="text-align: center; width: 400px; margin-bottom: 20px" >
            <label>{{ form.naziv.label_tag }}</label>
            <input type="text" required class="form-control" id="{{ form.naziv.id_for_label }}" name="{{ form.naziv.name }}" value="{{ form.naziv.value }}">
            {% if form.naziv.errors %}
                <div class="alert alert-danger">
                    <ul style="text-align: left">
                        {% for error in form.naziv.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
            <input type="submit" class="btn btn-primary btn-lg" value="Sacuvaj" style=" width: 370px; margin-top: 20px"/>
        </div>
    </form>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <script>
        kita = function (){
            return 2
        }

        var config = {
          type: 'pie',
          data: {
            datasets: [{
              data: {{ data|safe }},
              backgroundColor: ['#32a852', '#a84432', '#3240a8', '#3277a8', '#3240a8']
            }],
            labels: {{ labels|safe }}
          },
          options: {
            responsive: true
          }
        };

        window.onload = function() {
          var ctx = document.getElementById('pie-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };

      </script>

{% endblock %}

oglasise2/oglasise/oglasi/templates/komentari.html
{%  extends 'master.html' %}

{% block title %}
   Kategorije
{% endblock %}

{%  block content %}
    <h2>KOMENTARI </h2>
    <br>
    <div>
        <h3>Raspodela broja komentara po oglasima:</h3>
        <canvas id="chart" ></canvas>
        <br>
        <h3>Svi komentari:</h3>
        <table class="table ">
          <thead style="background-color: #215987; color: #e5e1dc">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Oglas</th>
                <th scope="col">Ocena</th>
                <th scope="col">Tekst</th>
                <th scope="col">Korisnik</th>

            </tr>
          </thead>
          <tbody>
            {% for k in komentari %}
                <tr style="transform: rotate(0);">
                    <td>{{ k.id }}</td>
                    <td>{{ k.oglas.naslov }}</td>
                    <td>{{ k.ocena }}</td>
                    <td>{{ k.tekst }}</td>
                    <td>{{ k.korisnik.username }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        let $1 = $(function () {
            const $populationChart = $("#chart");
            const ctx = $populationChart[0].getContext("2d");
            new Chart(ctx, {
                    type: 'bar',
                    data: {
                      labels: {{ labels|safe }},
                      datasets: [{
                        label: 'broj komentara',
                        backgroundColor: '#037ffc',
                        data: {{data|safe}}
                      }]
                    },
                    options: {
                      responsive: true,
                      legend: {
                        position: 'top',
                      },
                    }
                  });



            });
  </script>







{% endblock %}

oglasise2/oglasise/oglasi/templates/korisnici.html
{%  extends 'master.html' %}

{% block title %}
   Kategorije
{% endblock %}

{%  block content %}
    <h2>KORISNICI </h2>
    <br>
    <div>
        <h3>Raspodela broja oglasa po korisnicima:</h3>
        <canvas id="chart1" ></canvas>
        {{ data }}
        <h3>Prosečne ocene korisnika:</h3>
        <canvas id="chart2" ></canvas>
        <br>
        <h3>Svi korisnici:</h3>
        <table class="table ">
          <thead style="background-color: #215987; color: #e5e1dc">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Usermane</th>
                <th scope="col">Ime</th>
                <th scope="col">Prezime</th>
                <th scope="col">e-mail</th>

            </tr>
          </thead>
          <tbody>
            {% for k in korisnici %}
                <tr style="transform: rotate(0);">
                    <td>{{ k.id }}</td>
                    <td>{{ k.username }}</td>
                    <td>{{ k.first_name }}</td>
                    <td>{{ k.last_name }}</td>
                    <td>{{ k.email }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>

    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        let $1 = $(function () {
            const $Chart2 = $("#chart2");
            const ctx2 = $Chart2[0].getContext("2d");
            new Chart(ctx2, {
                    type: 'bar',
                    data: {
                      labels: {{ labels|safe }},
                      datasets: [{
                        label: 'prosečna ocena',
                        backgroundColor: '#037ffc',
                        data: {{ data2|safe }}
                      }]
                    },
                    options: {
                      responsive: true,
                      legend: {
                        position: 'top',
                      },
                    }
                  });

            });
            const $Chart = $("#chart1");
            const ctx = $Chart[0].getContext("2d");
            new Chart(ctx, {
                    type: 'bar',
                    data: {
                      labels: {{ labels|safe }},
                      datasets: [{
                        label: 'broj oglasa',
                        backgroundColor: '#037ffc',
                        data: {{ data|safe }}
                      }]
                    },
                    options: {
                      responsive: true,
                      legend: {
                        position: 'top',
                      },
                    }
                  });




  </script>







{% endblock %}

oglasise2/oglasise/oglasi/templates/oglas.html
{% extends 'master.html' %}

{% block content %}
    <h2>DETALJI OGLASA </h2>
    <br>
    <div class="card">
        <div class="card-header">
            <h1>
                Naslov: {{ oglas.naslov }}
            </h1>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0" >
                <p>opis: {{ oglas.opis }}</p>
                <p>mesto: {{ oglas.mesto }}</p>
                <p>ukupno komentara: {{ komentari.count }}</p>
                 {% if komentari.count != 0%}
                    <p>prosečna ocena: {{ pocena }}</p>
                {%endif%}
                <footer class="blockquote-footer">
                    Korisnik:
                    <cite title="Source Title">
                        {{ oglas.korisnik.username }}
                    </cite>
                </footer>
            </blockquote>
        </div>
    </div>
    <br>
    <div>
        {% if komentari.count != 0%}
            <h3>Raspodela ocena:</h3>
            <canvas id="pie-chart"></canvas>
        {%endif%}
        <br>
        <h3>Komentari:</h3>
        <table class="table ">
          <thead style="background-color: #215987; color: #e5e1dc">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Oglas</th>
                <th scope="col">Ocena</th>
                <th scope="col">Tekst</th>
                <th scope="col">Korisnik</th>
            </tr>
          </thead>
          <tbody>
            {% for k in komentari %}
                <tr style="transform: rotate(0);">
                    <td>{{ k.id }}</td>
                    <td>{{ k.oglas.naslov }}</td>
                    <td>{{ k.ocena }}</td>
                    <td>{{ k.tekst }}</td>
                    <td>{{ k.korisnik.username }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>


    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>
        kita = function (){
            return 2
        }
        var config = {
          type: 'pie',
          data: {
            datasets: [{
              data: {{ data|safe }},
              backgroundColor: ['#32a852', '#a84432', '#3240a8', '#3277a8', '#fcba03','#8403fc', '#fc037f']
            }],
            labels: {{ labels|safe }}
          },
          options: {
            responsive: true
          }
        };

        window.onload = function() {
          var ctx = document.getElementById('pie-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };
      </script>


{% endblock %}

oglasise2/oglasise/oglasi/templates/s_add.html
{%  extends 'master.html' %}

{% block title %}
    Add successfully!
{% endblock %}

{%  block content %}
    <h3> Kategorija uspešno dodata! </h3>
    <br>
    <div>
        <a href="{% url 'oglasi_app:kategorije'%}">Vrati se na kategorije</a>
    </div>
    <div>
        <a href="{% url 'oglasi_app:svi_oglasi'%}">Vrati se na početnu stranicu</a>
    </div>

{% endblock %}

oglasise2/oglasise/oglasi/templates/s_delete.html
{%  extends 'master.html' %}

{% block title %}
    Delete successfully!
{% endblock %}

{%  block content %}
    <h3> Kategorija uspešno obrisana </h3>
    <br>
    <div>
        <a href="{% url 'oglasi_app:kategorije'%}">Vrati se na kategorije</a>
    </div>
    <div>
        <a href="{% url 'oglasi_app:svi_oglasi'%}">Vrati se na početnu stranicu</a>
    </div>

{% endblock %}

oglasise2/oglasise/oglasi/templates/s_edit.html
{%  extends 'master.html' %}

{% block title %}
    Delete successfully!
{% endblock %}

{%  block content %}
    <h3> Kategorija uspešno izmenjena </h3>
    <br>
    <div>
        <a href="{% url 'oglasi_app:kategorije'%}">Vrati se na kategorije</a>
    </div>
    <div>
        <a href="{% url 'oglasi_app:svi_oglasi'%}">Vrati se na početnu stranicu</a>
    </div>

{% endblock %}

oglasise2/oglasise/oglasi/templates/svi_oglasi.html
{%  extends 'master.html' %}

{% block title %}
   Svi oglasi (home)
{% endblock %}

{%  block content %}
    <h2>OGLASI </h2>
    <br>

    <div>
        <h3>Raspodela oglasa po mestima:</h3>
        <canvas id="pie-chart"></canvas>
        <br>
        <h3>Svi oglasi:</h3>
        <h5>(vidi detalje klikom na oglas)</h5>
        <table class="table table-hover">
          <thead style="background-color: #215987; color: #e5e1dc">
            <tr>
                <th scope="col">id</th>
                <th scope="col">Naslov</th>
                <th scope="col">Kategorija</th>
                <th scope="col">Mesto</th>
                <th scope="col">Datum dodavanja</th>
                <th scope="col">Korisnik</th>
            </tr>
          </thead>
          <tbody>
            {% for oglas in oglasi %}
                <tr style="transform: rotate(0);">
                    <th scope="row"><a href="{% url 'oglasi_app:oglas' oglas.id %}" class="stretched-link">{{ oglas.id }}</a></th>
                    <td>{{ oglas.naslov }}</td>
                    <td>{{ oglas.kategorija.naziv }}</td>
                    <td>{{ oglas.mesto }}</td>
                    <td>{{ oglas.datumDodavanja }}</td>
                    <td>{{ oglas.korisnik.username }}</td>

                </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <script>
        kita = function (){
            return 2
        }

        var config = {
          type: 'pie',
          data: {
            datasets: [{
              data: {{ data|safe }},
              backgroundColor: ['#32a852', '#a84432', '#3240a8', '#3277a8', '#fcba03','#8403fc', '#fc037f']
            }],
            labels: {{ labels|safe }}
          },
          options: {
            responsive: true
          }
        };

        window.onload = function() {
          var ctx = document.getElementById('pie-chart').getContext('2d');
          window.myPie = new Chart(ctx, config);
        };

      </script>

{% endblock %}

oglasise2/oglasise/templates/header.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light " style="background-color:  #e8ce0c">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
       <ul class="navbar-nav">
            <a class="nav-item">
                <a class="nav-link" style="font-size: 110%; " href="{% url 'oglasi_app:svi_oglasi' %}" >
                    <img src="{% static 'img/repairman.png' %}" width="22" height="22" class="d-inline-block align-top" alt="logo"/>
                    <b>OGLASI </b>
                </a>
            </a>
       </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                    <a class="nav-link" style="font-size: 110%" href="{% url 'oglasi_app:komentari' %}"><b>KOMENTARI</b></a>
            </li>
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                    <a class="nav-link" style="font-size: 110%" href="{% url 'oglasi_app:kategorije' %}"><b>KATEGORIJE</b></a>
            </li>
        </ul>

        <ul class="navbar-nav">
            <li class="nav-item">
                    <a class="nav-link" style="font-size: 110%" href="{% url 'oglasi_app:korisnici' %}"><b>KORISNICI</b></a>
            </li>
        </ul>
    </div>



</nav>

oglasise2/oglasise/templates/master.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
                {{ page_title|default:"Untitled Page" }}
            {% endblock title %}
        </title>

        <link rel="shortcut icon" type="image/png" href="{% static 'repairman.ico' %}"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    </head>

    <body>

        <div class="container" style="text-align: center">
            <div style="background-image: url('https://i.imgur.com/rZQhgGS.png');">
                <h1 style="text-align:left; color: #e8ce0c; font-size: 450%; padding-left: 20px; padding-top: 100px" > OglaSi_Se  </h1>
                <h1 style="text-align:left; color: #e5e1dc; font-size: 180%; padding-left: 20px" > Najveća online platforma za oglašavanje zanatskih delatnosti. </h1>
                <h1 style="text-align:left; color: #e5e1dc; font-size: 180%; padding-left: 20px; padding-bottom: 15px" > Admin/Statistics panel: </h1>

            </div>
        </div>

        <div class="container" style="text-align: center; margin-top: 3px ">
            {% include 'header.html' %}
        </div>

        <div class="container" style="text-align: center; margin-top: 50px">
            {% block content %}
                <p>Placeholder text in base template. Replace with page content.</p>
            {% endblock content %}
        </div>

    </body>
</html>